### ISSUE TITLE
New Issues mainly for Mobile Device

### ISSUE THREAD

**Issue by GROSANIA** [Devcltratech/delctratech#1]
There's appeared to be some compitability and loading time issues, please tell me if you know can fix it.
some cause that i know ;
> Fixed width on biocard.
> Background Image size is too big.

**Comment by TirthaAhmadNazuha** [comment]
You can resize image manually and use html `<picture>` tag to display image according to media query or you can say max/min screen width set to show image with sufficient resolution and not excessive. for the tutorial see [this](https://www.w3schools.com/tags/tag_picture.asp)

**Comment by GROSANIA** [comment]
> You can resize image manually and use html `<picture>` tag to display image according to media query or you can say max/min screen width set to show image with sufficient resolution and not excessive. for the tutorial see [this](https://www.w3schools.com/tags/tag_picture.asp)

thanks to for give the solution, there's still an issues... on some devices that have smaller screen resolution the Biocard is Overlapping from the main screen, at this point we might need to reassemble the Web codes.

**Comment by TirthaAhmadNazuha** [comment]
In Biocard it's overWidth, because you add padding and it's also 100% or full width so the actual size is 100% plus 2 times your padding. So add it `box-sizing: border-box;` in your css.
